plugin:
    name: 'stefan.gallery::lang.plugin.name'
    description: 'stefan.gallery::lang.plugin.description'
    author: Stefan
    icon: oc-icon-camera
    homepage: ''
permissions:
    stefan.gallery.galleries:
        tab: 'stefan.gallery::lang.permissions.galleries.title'
        label: 'stefan.gallery::lang.permissions.galleries.label'
navigation:
    stefan-gallery-galleries:
        label: 'stefan.gallery::lang.menues.main.gallery'
        url: stefan/gallery/gallery
        icon: icon-camera
        permissions:
            - 'stefan.gallery.*'
        sideMenu:
            stefan-gallery-galleries-menu:
                label: 'stefan.gallery::lang.menues.side.galleries'
                url: stefan/gallery/gallery
                icon: icon-camera
                permissions:
                    - stefan.gallery.galleries
