name: Tag
form: $/stefan/gallery/models/tag/fields.yaml
modelClass: Stefan\Gallery\Models\Tag
defaultRedirect: stefan/gallery/tag
create:
    redirect: 'stefan/gallery/tag/update/:id'
    redirectClose: stefan/gallery/tag
update:
    redirect: stefan/gallery/tag
    redirectClose: stefan/gallery/tag
