title: Tag
modelClass: Stefan\Gallery\Models\Tag
list: $/stefan/gallery/models/tag/columns.yaml
recordUrl: 'stefan/gallery/tag/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '10'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: title
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
