list: $/stefan/gallery/models/image/columns.yaml
modelClass: Stefan\Gallery\Models\Image
title: Image
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
        mode: exact
recordUrl: 'stefan/gallery/image/update/:id'
defaultSort:
  column: order_by
  direction: asc